name: GitHub Auto Refresh Bot

on:
  schedule:
    - cron: "*/2 * * * *"  # Run every 6 hours
  workflow_dispatch:        # Allow manual trigger

jobs:
  run-refresh-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 120    # Set maximum runtime to 6 hours
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install Puppeteer dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libnss3 libatk-bridge2.0-0 libx11-xcb1 libxcomposite1 libxdamage1 libxrandr2 libgbm1 libasound2 libpangocairo-1.0-0 libgtk-3-0

      - name: Run GitHub Refresh Bot with Retry
        run: |
          RETRY_COUNT=0
          until [ "$RETRY_COUNT" -ge 10 ]
          do
            node index.js --no-sandbox --disable-setuid-sandbox && break
            RETRY_COUNT=$((RETRY_COUNT+1))
            echo "Retrying... ($RETRY_COUNT/10)"
            sleep 5
          done

      - name: Create a dummy commit
        run: |
          echo "Commit made on $(date)" >> commit.log
          git config --global user.name "thinakaranmanokaran"
          git config --global user.email "thinakaranmanohar@yahoo.com"
          git add commit.log
          git commit -m "Daily commit on $(date)"
          git push
